AllCops:
  TargetRubyVersion: 3.0.4

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

Layout/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 20

Style/NumericLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
