AllCops:
  TargetRubyVersion: 3.0.4

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/NumericLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
